sudo: required
services:
  - docker

before_install:
  - docker build -t udeep/docker-react -f Dockerfile.dev .

script:
  - docker run udeep/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-258148218765"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
